# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -H 'Content-Type: application/json' \
         -H "Authorization: Token $(VALOHAI_API_TOKEN)" \
         -X POST \
         -d '{"project": "tensorflow-azure-pipelines", \
              "commit": "$(GIT_SHA)", \
              "step": "Preprocess dataset (MNIST)" }'
         https://app.valohai.com/api/v0/executions/
  displayName: 'Trigger a Valohai execution'
  env:
    GIT_SHA: $(Build.SourceVersion)